user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            default_type text/plain;
            return 200 "Hello from NGINX OSS onboarded to NIM\n";
        }
    }

    server {
        listen 8081;

        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            deny all;
        }
    }
}